services:
  mcaddon-manager:
    build: .
    image: zuptalo/mcaddon-manager:latest
    container_name: mcaddon-manager
    ports:
      - "8000:8000"
    volumes:
      # Mount your existing Minecraft data directory
      - /root/tools/minecraft:/root/tools/minecraft
      # Mount Docker socket to allow container restarts
      - /var/run/docker.sock:/var/run/docker.sock
      # Mount timezone for consistency
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - prod-network
    restart: unless-stopped

networks:
  prod-network:
    external: true